### ISSUE TITLE
Spacing Issue

### ISSUE THREAD

**Issue by Alcatraz077** [B-Software/Ward#15]
Built via jar file, seeing some spacing issues.

On Firefox 68.9EBR running Debian 10: 
![Ward-Firefox68 9EBR-Debian10](https://user-images.githubusercontent.com/21212254/84831608-45b9b900-aff1-11ea-9307-b716f8974ade.png)

On Firefox 77.01 (64bit) running Windows 10.
![Ward-Firefox-Win10](https://user-images.githubusercontent.com/21212254/84831611-46524f80-aff1-11ea-98cd-227855289650.png)

**Comment by Rudolf-Barbu** [comment]
Now it should work proprrly

**Comment by Alcatraz077** [comment]
Deployed the new release, still showing the same spacing issues on Windows 10 with Firefox. Tried out via a Private Window as well, just to be sure.

**Comment by Rudolf-Barbu** [comment]
I gues I finally understood whats was the problem. Wrong wont format. Can you please try 1.2.3 release

**Comment by Alcatraz077** [comment]
1.2.3 seems to fix it! Thanks!
