### ISSUE TITLE
GPU monitoring

### ISSUE THREAD

**Issue by moinnadeem** [B-Software/Ward#25]
Hi, this is fantastic!

I would like to discuss how feasible it would be to add GPU monitoring to this service; ie. I would like to add a block that displayed GPU utilization / how many are use. Is that easy to add? How extensible is this to add a new block? I would be willing to spend roughly one day to hack on this.

Thanks!

**Comment by Rudolf-Barbu** [comment]
Sorry for a long delay, i will add this info in the paginator, which appeared in v1.7.0. Among with network info. Of course, if OSHI can get GPU info. I will provide a research in OSHI docs.

**Comment by Rudolf-Barbu** [comment]
Oshi can only get name od video adapter, but not the usage.
