### ISSUE TITLE
Not reading RAM correctly on Synology NAS

### ISSUE THREAD

**Issue by geekaroni** [B-Software/Ward#3]
Popped the files on my Synology NAS. Everything was correct but the RAM. It was pegging out at 96% when the DSM was reading only 20% usage.

**Comment by Catbirby** [comment]
I have the same issue on a VPS. The VPS has 2GiB of RAM but only 1GiB is being reported

**Comment by Rudolf-Barbu** [comment]
> Popped the files on my Synology NAS. Everything was correct but the RAM. It was pegging out at 96% when the DSM was reading only 20% usage.

Maybe problem is that project shows available ram amount, it's not same as free, 'cause free is a "exactly not used ram" it's does not see cached ram, by example. But available takes cache into account. I was checking for values with PhpSysInfo to be the same.

**Comment by Rudolf-Barbu** [comment]
But still project was migrated to java with external lib, i think this should solve the problem
