### ISSUE TITLE
Passing application port via environment variable

### ISSUE THREAD

**Issue by zekroTJA** [B-Software/Ward#38]
Hey! 

First of all: awesome project!

I installed it using Docker on my VPS behind Traefik as edge router and I noticed that the initialization-step is a bit unhandy in this particular use case because I need an open port to specify the application port which is then routed via Traefik.

It would be awesome if the initialization step could be bypassed by using predefined environment variables to set the initialization parameters.

For eyample:
```
WARD_SERVERNAME="My Server"
WARD_PORT="8080"
WARD_THEME="dark"
```

**Comment by Rudolf-Barbu** [comment]
Hello! You can use setup ini to baypass initialization step. When you initialize application it creates setup ini with all parameters, so you can just copy and paste it for new instance. The path depends on you OS
