### ISSUE TITLE
.war file leads to 404, ubuntu 18.04, tomcat 9

### ISSUE THREAD

**Issue by Catbirby** [B-Software/Ward#5]
When uploading the .war file to a tomcat 9 server running on Ubuntu 18.04 I just get a 404 no matter what context path is chosen. Issue does not happen with other .war deploys.

**Comment by ScribbleNerd** [comment]
Same here, Ubuntu 20.04, tomcat 9

**Comment by Rudolf-Barbu** [comment]
I remade package from .war to .jar Please try this, and let me know if this solved the problem. Instructions for Ubuntu are in readme. (By default dashboard starts on port 80)

**Comment by Catbirby** [comment]
So now we've went from php to a tomcat server to a independent .jar that doesn't require tomcat? You've honestly lost me with the progression of this whole thing.
